name: Deploy Test Reports to GitHub Pages

on:
  workflow_run:
    workflows: ["Python Testing Demo - Automated Tests"]
    types:
      - completed
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: 📦 Install dependencies
        run: |
          pip install pytest pytest-html pytest-cov

      - name: 🧪 Generate fresh reports
        run: |
          mkdir -p public
          pytest test_main.py -v \
            --html=public/test-report.html \
            --self-contained-html \
            --cov=main \
            --cov-report=html:public/coverage

      - name: 🏗️ Create index page
        run: |
          cat > public/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Python Testing Demo - Live Reports</title>
              <style>
                  body { 
                      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
                      margin: 0; 
                      padding: 40px; 
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      min-height: 100vh;
                  }
                  .container { 
                      max-width: 800px; 
                      margin: 0 auto; 
                      background: white; 
                      padding: 40px; 
                      border-radius: 15px; 
                      box-shadow: 0 10px 30px rgba(0,0,0,0.2);
                  }
                  .header { 
                      text-align: center; 
                      color: #2c3e50; 
                      margin-bottom: 40px;
                  }
                  .header h1 { 
                      font-size: 2.5em; 
                      margin-bottom: 10px;
                      background: linear-gradient(45deg, #3498db, #2ecc71);
                      -webkit-background-clip: text;
                      -webkit-text-fill-color: transparent;
                  }
                  .links { 
                      display: grid; 
                      grid-template-columns: 1fr 1fr; 
                      gap: 20px; 
                      margin: 30px 0;
                  }
                  .link-card { 
                      background: linear-gradient(135deg, #3498db, #2ecc71); 
                      color: white; 
                      padding: 30px; 
                      text-decoration: none; 
                      border-radius: 10px; 
                      text-align: center;
                      transition: transform 0.3s, box-shadow 0.3s;
                      display: block;
                  }
                  .link-card:hover { 
                      transform: translateY(-5px);
                      box-shadow: 0 15px 35px rgba(52, 152, 219, 0.4);
                  }
                  .link-card h3 { 
                      margin: 0 0 10px 0; 
                      font-size: 1.3em;
                  }
                  .link-card p { 
                      margin: 0; 
                      opacity: 0.9;
                  }
                  .stats { 
                      background: #f8f9fa; 
                      padding: 20px; 
                      border-radius: 10px; 
                      margin: 30px 0;
                      text-align: center;
                  }
                  .stat { 
                      display: inline-block; 
                      margin: 0 20px;
                  }
                  .stat-value { 
                      font-size: 2em; 
                      font-weight: bold; 
                      color: #27ae60;
                  }
                  .stat-label { 
                      font-size: 0.9em; 
                      color: #7f8c8d;
                  }
                  .footer {
                      text-align: center;
                      margin-top: 40px;
                      padding-top: 20px;
                      border-top: 1px solid #ecf0f1;
                      color: #7f8c8d;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <div class="header">
                      <h1>🐍 Python Testing Demo</h1>
                      <p>Automated Test Reports - Live from GitHub Actions</p>
                  </div>

                  <div class="stats">
                      <div class="stat">
                          <div class="stat-value">5</div>
                          <div class="stat-label">Tests</div>
                      </div>
                      <div class="stat">
                          <div class="stat-value">100%</div>
                          <div class="stat-label">Success Rate</div>
                      </div>
                      <div class="stat">
                          <div class="stat-value">⚡</div>
                          <div class="stat-label">Fast</div>
                      </div>
                  </div>

                  <div class="links">
                      <a href="test-report.html" class="link-card">
                          <h3>📊 Test Report</h3>
                          <p>Detailed test results with pass/fail status</p>
                      </a>
                      <a href="coverage/index.html" class="link-card">
                          <h3>📈 Coverage Report</h3>
                          <p>Code coverage analysis and metrics</p>
                      </a>
                  </div>

                  <div class="footer">
                      <p>🚀 Generated automatically by GitHub Actions</p>
                      <p>Perfect for teaching CI/CD and automated testing!</p>
                  </div>
              </div>
          </body>
          </html>
          EOF

      - name: 🔧 Setup Pages
        uses: actions/configure-pages@v3

      - name: 📤 Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './public'

      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
